apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: GRACEFUL_TIMEOUT
              value: "120"
            - name: KEEP_ALIVE
              value: "120"
            - name: MAX_WORKERS
              value: "4"
            - name: TIMEOUT
              value: "120"
            - name: WEB_CONCURRENCY
              value: "1"
            - name: WORKERS_PER_CORE
              value: "0.25"
            - name: WORKER_CLASS
              value: uvicorn.workers.UvicornWorker
          image: backend
          name: fastapi-app
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
