apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: fronend
  name: fronend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fronend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: fronend
    spec:
      containers:
        - env:
            - name: deployment
              value: docker
          image: fronend
          name: streamlit-app
          ports:
            - containerPort: 8501
          resources: {}
      restartPolicy: Always
status: {}
